name: Daily Prediction Workflow

on:
  schedule:
   # - cron: "30 7 * * *"  # This means 7:30 AM UTC every day
  workflow_dispatch: # You can also manually trigger the workflow

jobs:
  daily_prediction:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository on main branch
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Use the Python version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Fetch Data from API and Make Prediction
      - name: Fetch Data from API and Make Prediction
        run: |
          python prediction.py  # This will update the index.html file with new predictions

      # Step 5: Create and Checkout a fresh gh-pages branch
      - name: Checkout fresh gh-pages branch
        run: |
          # Create and switch to a new gh-pages branch
          git checkout --orphan gh-pages
          git rm -rf .  # Remove all files (except for those that will be updated)

      # Step 6: Commit and push prediction
      - name: Commit and push prediction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git user
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Stage and commit the updated index.html file
          git add index.html
          git commit -m "Update prediction" || echo "No changes to commit"

          # Push to the gh-pages branch using the Personal Access Token (PAT)
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/PD-BDS/MLOps.git HEAD:gh-pages --force
